# Generated by Django 3.1 on 2020-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200902_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_src',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
