# Generated by Django 3.1 on 2020-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_image_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='zzz', upload_to='products/'),
        ),
    ]
