# Generated by Django 3.1 on 2020-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0003_auto_20200921_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default_user.svg', upload_to='profile_pics'),
        ),
    ]
