# Generated by Django 3.1 on 2020-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0004_auto_20200921_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user.svg', upload_to='profile_pics'),
        ),
    ]
